Fix "Extract artifact"; assert expected changes
The `npm pack` output puts everything into `package/`. Strip
the leading `package` prefix and extract into the repository
root.

Fail if we overwrote something unexpected with a change:
- package.json is expected to change (version bump)
- `lib/**` is loosely expected to change (.ts files generate
  .js files, which get formatted with prettier)

We could assert that only the .js files that correspond to .ts
files have changed, but this is enough to avoid overwriting any
of the build infrastructure.

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -118,14 +118,17 @@ jobs:
         with:
           subject-path: ${{ needs.build.outputs.tarball }}
 
-      # incorporate the auto-format changes and version bump from
-      # the artifact into the repository by re-extracting the published
-      # files into the source directory
+      # extract the contents of the artifact we will publish back into the
+      # git root so that we can commit back the version bump and formatted
+      # typescript output. assert that the only changes are to package.json
+      # and lib/** to limit the blast radius of any errors
       - name: Extract artifact
         run: |
-          tar zxf "${{ needs.build.outputs.tarball }}"
-          git diff --name-only
-          exit 1
+          tar zxf "${{ needs.build.outputs.tarball }}" --strip-components=1 -C .
+          if git diff --name-only HEAD -- ':(exclude)lib/**' ':(exclude)package.json'; then
+            echo "Tarball contained unexpected differences, aborting"
+            exit 1
+          fi
 
       - name: Commit and push
         run: |
@@ -134,7 +137,6 @@ jobs:
           git tag "v$(node -p "require('./package.json').version")"
           echo :::: git push
           echo :::: git push --tags
-
       - name: Publish to npm
         run: |
           echo :::: npm publish --provenance --access public
