Lock down the automatic publishing workflow
- Pin versions of build tools that we use, but ensure they
  conform to the semver specs in package.json
- Enforce that CI environments can _either_ run code from
  dependencies _or_ have privileged write access but not both
- Link jobs together with outputs and artifacts

The actual commit/publish step is nerfed temporarily to prevent
accidents and allow an initial review

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -8,20 +8,61 @@ on:
       - master
 
 jobs:
-  publish:
-    if: github.event.pull_request.merged == true && (contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'major'))
+  # initial validation: determine whether to run the jobs at all, and
+  # define parameters
+  gate:
+    # do nothing unless the PR got merged. dependent jobs won't run
+    if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
 
+    # no permissions necessary
+    permissions: {}
+
+    # determine the semver bump to perform later, according to the PR labels.
+    # empty output will prevent the build job (and its dependent jobs) from
+    # running
+    outputs:
+      bump: ${{ steps.version.outputs.bump }}
+    steps:
+      - name: Determine version bump
+        id: version
+        # only output known string literals; do not include user-supplied data.
+        # create this value in one place with clearly reviewable logic
+        run: |
+          if ${{ contains(github.event.pull_request.labels.*.name, 'major') }}; then
+            echo "bump=major" >> $GITHUB_OUTPUT
+          elif ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}; then
+            echo "bump=minor" >> $GITHUB_OUTPUT
+          elif ${{ contains(github.event.pull_request.labels.*.name, 'patch') }}; then
+            echo "bump=patch" >> $GITHUB_OUTPUT
+          else
+            echo "bump="
+          fi
+
+  # non-privileged context: do the work of producing a build artifact, but make
+  # no direct commits or publishes
+  build:
+    runs-on: ubuntu-latest
+    needs: gate
+    # empty bump = do not publish, skip this job (and dependent jobs)
+    if: needs.gate.outputs.bump != ''
+
+    # untrusted context. no write permissions
     permissions:
-      contents: write
-      id-token: write
+      contents: read
+
+    # the NPM tarball is the only input into the privileged publish step.
+    # the contents will not be _executed_ in the CI runner, insulating us
+    # against infrastructure compromise, but if the build step includes a
+    # malicious dependency the published artifact will still be compromised.
+    # we may be able to add a scanning step between build and publish to help
+    # catch any such problem before pushing it out to users
+    outputs:
+      tarball: ${{ steps.build.outputs.tarball }}
 
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v6
-        with:
-          fetch-depth: 0
-          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Setup Node
         uses: actions/setup-node@v6
@@ -30,41 +71,71 @@ jobs:
           package-manager-cache: false
           registry-url: 'https://registry.npmjs.org'
 
+      - name: Build for release
+        id: build
+        run: ./scripts/build-for-release.sh "${{ needs.gate.outputs.bump }}"
+
+      # hand off built artifact to privileged publish job
+      - name: Upload artifact
+        # v6 fails with "crypto is not defined" -- node version problem?
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ steps.build.outputs.tarball }}
+          path: ${{ steps.build.outputs.tarball }}
+          if-no-files-found: error
+
+  # privileged context: push commits to repo, publish to npm
+  publish:
+    runs-on: ubuntu-latest
+    needs: build
+
+    # privileged context. Avoid executing code from dependencies and/or third-party actions
+    permissions:
+      contents: write # Allow job to commit to repository
+      id-token: write # Allow job to obtain OIDC tokens (publish to NPM)
+      attestations: write # Allow job to create artifact attestations
+      # act doesn't support this yet, for testing in act we'll need to temporarily disable it
+      artifact-metadata: write # Allow job to write artifact attestations
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 1
+          token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Configure Git
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Install dependencies
-        run: npm install
+      - name: Download artifact
+        uses: actions/download-artifact@v5
+        with:
+          name: ${{ needs.build.outputs.tarball }}
+          path: .
 
-      - name: Build
-        run: npm run build
+      - uses: actions/attest-build-provenance@v3
+        with:
+          subject-path: ${{ needs.build.outputs.tarball }}
 
-      - name: Determine version bump
-        id: version
+      # incorporate the auto-format changes and version bump from
+      # the artifact into the repository by re-extracting the published
+      # files into the source directory
+      - name: Extract artifact
         run: |
-          if ${{ contains(github.event.pull_request.labels.*.name, 'major') }}; then
-            echo "bump=major" >> $GITHUB_OUTPUT
-          elif ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}; then
-            echo "bump=minor" >> $GITHUB_OUTPUT
-          else
-            echo "bump=patch" >> $GITHUB_OUTPUT
-          fi
-
-      - name: Bump version
-        run: npm version ${{ steps.version.outputs.bump }} --no-git-tag-version
-
-      - name: Fix formatting
-        run: npm run format
+          tar zxf "${{ needs.build.outputs.tarball }}"
+          git diff --name-only
+          exit 1
 
       - name: Commit and push
         run: |
           git add .
           git commit -m "chore: release v$(node -p "require('./package.json').version")"
           git tag "v$(node -p "require('./package.json').version")"
-          git push
-          git push --tags
+          echo :::: git push
+          echo :::: git push --tags
 
       - name: Publish to npm
-        run: npm publish --provenance --access public
+        run: |
+          echo :::: npm publish --provenance --access public
